# Generated by Django 3.0.7 on 2020-07-05 05:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('tittle', models.CharField(max_length=50, verbose_name='Titulo')),
                ('cover', models.ImageField(upload_to='portada', verbose_name='Portada')),
                ('description', models.CharField(max_length=50, verbose_name='Descripcion')),
                ('body', models.CharField(max_length=200, verbose_name='Cuepo')),
                ('footer', models.CharField(max_length=50, verbose_name='Footer')),
            ],
            options={
                'verbose_name': 'Noticias',
                'verbose_name_plural': 'Noticias',
                'db_table': 'Noticia',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('tittle', models.CharField(max_length=50, verbose_name='Titulo')),
                ('body', models.CharField(max_length=50, verbose_name='Cuerpo')),
                ('icon', models.ImageField(upload_to='iconos', verbose_name='Icono')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Admin', verbose_name='Administrador')),
                ('user', models.ManyToManyField(to='user.User', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'Notification',
            },
        ),
    ]
